import {
  Client,
  Contract,
  FinancialTransaction,
  FollowUpItem,
  HistoricalProject,
  Lead,
  MessageLog,
  MessageSequence,
  Niche,
  Opportunity,
  Project,
  Proposal,
  Service,
  TaskItem,
  BusinessInsight,
  Prospect,
  BusinessContext,
  CommercialGoal,
  ConversationSummary,
  NextBestAction,
  EvoInsightItem,
  AICommand,
  AIActionLog,
} from '@/types/database';


export const INITIAL_SERVICES: Service[] = [
  // WEBSITES
  {
    id: 'srv-1',
    name: 'Site Institucional',
    category: 'WEBSITES',
    description: 'Desenvolvimento web de alta performance com design autoral, SEO técnico e CMS integrado.',
    base_price: 3200,
    delivery_time_days: 14,
    status: 'ativo',
  },
  {
    id: 'srv-2',
    name: 'Landing Page de Alta Conversão',
    category: 'WEBSITES',
    description: 'Página única otimizada para campanhas de tráfego pago com copywriting persuasivo e tracking avançado.',
    base_price: 1800,
    delivery_time_days: 7,
    status: 'ativo',
  },
  {
    id: 'srv-3',
    name: 'Site Jurídico / Especializado',
    category: 'WEBSITES',
    description: 'Estrutura institucional alinhada ao código da OAB e posicionamento de autoridade em nichos regulados.',
    base_price: 3800,
    delivery_time_days: 15,
    status: 'ativo',
  },
  {
    id: 'srv-4',
    name: 'E-commerce Direto',
    category: 'WEBSITES',
    description: 'Loja virtual rápida com checkout transparente, gateway de pagamento e gestão de pedidos.',
    base_price: 5200,
    delivery_time_days: 25,
    status: 'ativo',
  },
  // AUTOMAÇÃO
  {
    id: 'srv-5',
    name: 'Automação WhatsApp & Atendimento',
    category: 'AUTOMAÇÃO',
    description: 'Fluxos automáticos via WhatsApp com qualificação de leads, roteamento e agendamento sem fricção.',
    base_price: 2400,
    delivery_time_days: 10,
    status: 'ativo',
  },
  {
    id: 'srv-6',
    name: 'Agente IA Especialista',
    category: 'AUTOMAÇÃO',
    description: 'Agente conversacional treinado na base de conhecimento da empresa para atendimento 24/7.',
    base_price: 3500,
    delivery_time_days: 14,
    status: 'ativo',
  },
  {
    id: 'srv-7',
    name: 'Follow-up Automático n8n',
    category: 'AUTOMAÇÃO',
    description: 'Régua inteligente de reengajamento automático para orçamentos e propostas pendentes.',
    base_price: 1900,
    delivery_time_days: 8,
    status: 'ativo',
  },
  {
    id: 'srv-8',
    name: 'Implantação de CRM & Processos',
    category: 'AUTOMAÇÃO',
    description: 'Estruturação do funil comercial, etapas de qualificação e métricas de conversão.',
    base_price: 2800,
    delivery_time_days: 12,
    status: 'ativo',
  },
  // PRESENÇA DIGITAL
  {
    id: 'srv-9',
    name: 'Google Meu Negócio & Otimização Local',
    category: 'PRESENÇA DIGITAL',
    description: 'Posicionamento dominante na busca local e Google Maps para captação de clientes na região.',
    base_price: 950,
    delivery_time_days: 5,
    status: 'ativo',
  },
  {
    id: 'srv-10',
    name: 'SEO Orgânico & Conteúdo Técnico',
    category: 'PRESENÇA DIGITAL',
    description: 'Construção de autoridade orgânica e rankeamento para palavras-chave de intenção de compra.',
    base_price: 1600,
    delivery_time_days: 30,
    status: 'ativo',
  },
  {
    id: 'srv-11',
    name: 'Manutenção & Evolução Contínua',
    category: 'PRESENÇA DIGITAL',
    description: 'Hospedagem de alta performance, atualizações de segurança, backup diário e melhorias técnicas contínuas.',
    base_price: 450,
    delivery_time_days: 30,
    status: 'ativo',
  },
  {
    id: 'srv-12',
    name: 'Consultoria Estratégica Digital',
    category: 'PRESENÇA DIGITAL',
    description: 'Diagnóstico de canais, funil comercial e plano de ação para aceleração de vendas.',
    base_price: 2200,
    delivery_time_days: 10,
    status: 'ativo',
  },
];

export const INITIAL_NICHES: Niche[] = [
  {
    id: 'niche-1',
    name: 'Contabilidade',
    description: 'Escritórios contábeis, BPO financeiro e consultorias tributárias.',
    status: 'ativo',
    sequences_count: 1,
  },
  {
    id: 'niche-2',
    name: 'Clínicas / Odonto / Estética',
    description: 'Clínicas médicas, odontológicas, dermatologia e estética avançada.',
    status: 'ativo',
    sequences_count: 1,
  },
  {
    id: 'niche-3',
    name: 'Imobiliárias',
    description: 'Imobiliárias, corretores autônomos de alto padrão e administradoras.',
    status: 'ativo',
    sequences_count: 1,
  },
  {
    id: 'niche-4',
    name: 'Advocacia',
    description: 'Escritórios jurídicos empresariais, trabalhistas e previdenciários.',
    status: 'ativo',
    sequences_count: 1,
  },
  {
    id: 'niche-5',
    name: 'Consultorias & Serviços B2B',
    description: 'Empresas de treinamento, consultoria de gestão e tecnologia.',
    status: 'ativo',
    sequences_count: 1,
  },
];

export const INITIAL_SEQUENCES: MessageSequence[] = [
  {
    id: 'seq-1',
    niche_id: 'niche-1',
    niche_name: 'Contabilidade',
    name: 'Prospecção Ativa BPO & Contabilidade',
    status: 'ativa',
    steps: [
      {
        id: 'step-1-1',
        sequence_id: 'seq-1',
        step_order: 1,
        name: 'Etapa 1 — Abertura Consultiva',
        message_text: 'Olá {nome}, tudo bem? Notei que a {empresa} tem forte atuação em {cidade}, mas ao pesquisar encontrei apenas um perfil básico sem canal de pré-qualificação ágil. Vocês hoje perdem muito tempo triando clientes que chegam pelo WhatsApp sem perfil financeiro?',
        wait_days: 2,
        channel: 'whatsapp',
        status: 'ativo',
      },
      {
        id: 'step-1-2',
        sequence_id: 'seq-1',
        step_order: 2,
        name: 'Etapa 2 — Follow-up 1 (Insight de Conversão)',
        message_text: '{nome}, passando rápido: na semana passada estruturamos um fluxo no WhatsApp para outro escritório que filtrou 65% das dúvidas repetitivas e já entregou o lead pronto com faturamento estimado. Faz sentido mostrar um resumo de 3 min em áudio ou vídeo?',
        wait_days: 3,
        channel: 'whatsapp',
        status: 'ativo',
      },
      {
        id: 'step-1-3',
        sequence_id: 'seq-1',
        step_order: 3,
        name: 'Etapa 3 — Follow-up 2 (Diagnóstico Direto)',
        message_text: '{nome}, imagino que sua rotina esteja corrida com o fechamento contábil. Se a prioridade no momento não for otimizar a captação e automação comercial da {empresa}, sem problemas! Caso queira revisitar mês que vem, estamos por aqui.',
        wait_days: 5,
        channel: 'whatsapp',
        status: 'ativo',
      },
      {
        id: 'step-1-4',
        sequence_id: 'seq-1',
        step_order: 4,
        name: 'Encerramento — Arquivamento Educado',
        message_text: '{nome}, para não ocupar seu tempo vou encerrar nossos contatos por aqui. Desejo sucesso no crescimento da {empresa}. Se um dia precisar acelerar a presença e automação digital, meu contato fica salvo!',
        wait_days: 0,
        channel: 'whatsapp',
        status: 'ativo',
      },
    ],
  },
  {
    id: 'seq-2',
    niche_id: 'niche-2',
    niche_name: 'Clínicas / Odonto / Estética',
    name: 'Captação & Agendamento Particular',
    status: 'ativa',
    steps: [
      {
        id: 'step-2-1',
        sequence_id: 'seq-2',
        step_order: 1,
        name: 'Etapa 1 — Abertura (Velocidade de Resposta)',
        message_text: 'Olá {nome}, tudo bem? Vi o posicionamento da {empresa} em {cidade}. Fiz um teste rápido na busca local e reparei que vocês não possuem confirmação e agendamento instantâneo via WhatsApp. Quantas consultas particulares acabam escapando por demora no retorno da recepção?',
        wait_days: 2,
        channel: 'whatsapp',
        status: 'ativo',
      },
      {
        id: 'step-2-2',
        sequence_id: 'seq-2',
        step_order: 2,
        name: 'Etapa 2 — Follow-up 1 (Estudo de Caso)',
        message_text: '{nome}, só para complementar: clínicas que automatizam a triagem inicial aumentam em média 38% o comparecimento e reduzem faltas com lembrete automático. Gostaria de ver o fluxo funcionando na prática?',
        wait_days: 3,
        channel: 'whatsapp',
        status: 'ativo',
      },
      {
        id: 'step-2-3',
        sequence_id: 'seq-2',
        step_order: 3,
        name: 'Etapa 3 — Follow-up 2 (Encerramento Gradual)',
        message_text: '{nome}, tudo bem? Acredito que a equipe já esteja bem atendida nesse quesito. Se quiser avaliar uma modernização do site ou automação mais adiante, fico à disposição!',
        wait_days: 4,
        channel: 'whatsapp',
        status: 'ativo',
      },
    ],
  },
  {
    id: 'seq-3',
    niche_id: 'niche-4',
    niche_name: 'Advocacia',
    name: 'Posicionamento Jurídico & Autoridade Digital',
    status: 'ativa',
    steps: [
      {
        id: 'step-4-1',
        sequence_id: 'seq-3',
        step_order: 1,
        name: 'Etapa 1 — Abertura (Autoridade e SEO Local)',
        message_text: 'Dr(a). {nome}, tudo bem? Acompanhei algumas decisões e menções da {empresa}. Notei que a presença digital de vocês no Google não reflete a relevância técnica dos casos que atendem em {cidade}. Vocês já recebem clientes qualificados diretamente pelo site institucional hoje?',
        wait_days: 3,
        channel: 'whatsapp',
        status: 'ativo',
      },
      {
        id: 'step-4-2',
        sequence_id: 'seq-3',
        step_order: 2,
        name: 'Etapa 2 — Follow-up 1 (Conformidade OAB)',
        message_text: 'Dr(a). {nome}, desenvolvemos plataformas jurídicas estritamente alinhadas ao Provimento da OAB, com foco em retenção de clientes corporativos. Gostaria de receber um diagnóstico de 2 minutos sobre o posicionamento atual da banca?',
        wait_days: 3,
        channel: 'whatsapp',
        status: 'ativo',
      },
    ],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Dr. Roberto Silva',
    company_name: 'Silva Advocacia',
    role: 'Sócio Fundador',
    segment: 'Advocacia',
    niche_id: 'niche-4',
    email: 'roberto@silvaadvocacia.com.br',
    phone: '(11) 98765-4321',
    whatsapp: '5511987654321',
    website: 'silvaadvocacia.com.br',
    city: 'São Paulo',
    state: 'SP',
    score: 92,
    temperature: 'quente',
    status: 'em_abordagem',
    services: ['Site Jurídico / Especializado', 'Google Meu Negócio & Otimização Local'],
    last_contact_at: '2026-09-13T14:30:00Z',
    next_action: 'Aguardando retorno da mensagem de abertura há 2 dias',
    next_action_at: '2026-09-15T18:00:00Z',
    sequence_progress: {
      id: 'seq-prog-1',
      lead_id: 'lead-1',
      sequence_id: 'seq-3',
      sequence_name: 'Posicionamento Jurídico & Autoridade Digital',
      current_step_id: 'step-4-1',
      current_step_name: 'Etapa 1 — Abertura (Autoridade e SEO Local)',
      current_step_order: 1,
      status: 'aguardando_resposta',
      last_sent_at: '2026-09-13T14:30:00Z',
      next_due_at: '2026-09-16T10:00:00Z',
    },
    ai_analysis: {
      data_points: [
        'Site atual é antigo (layout de 2018 não responsivo)',
        'Não possui certificado SSL ativo em algumas páginas',
        'Avaliação 4.8 no Google Meu Negócio mas apenas 6 avaliações',
      ],
      inferences: [
        'Provável perda de leads corporativos vindos de buscas empresariais',
        'Decisor costuma ser acessível diretamente via WhatsApp',
      ],
      recommendations: [
        'Oferecer redesenho institucional premium focado em compliance empresarial',
        'Vincular otimização do perfil Google Maps para busca regional',
      ],
      main_hook: 'Modernização institucional com conformidade OAB e velocidade mobile',
      should_approach: true,
    },
  },
  {
    id: 'lead-2',
    name: 'Dra. Camila Vasconcelos',
    company_name: 'Clínica Vida',
    role: 'Diretora Clínica',
    segment: 'Clínicas / Odonto / Estética',
    niche_id: 'niche-2',
    email: 'contato@clinicavidasaude.com.br',
    phone: '(19) 99123-8877',
    whatsapp: '5519991238877',
    website: 'clinicavidasaude.com.br',
    city: 'Campinas',
    state: 'SP',
    score: 88,
    temperature: 'quente',
    status: 'em_conversa',
    services: ['Landing Page de Alta Conversão', 'Automação WhatsApp & Atendimento'],
    last_contact_at: '2026-09-14T11:00:00Z',
    next_action: 'Proposta de R$ 3.500 aguardando retorno',
    next_action_at: '2026-09-16T14:00:00Z',
    sequence_progress: {
      id: 'seq-prog-2',
      lead_id: 'lead-2',
      sequence_id: 'seq-2',
      sequence_name: 'Captação & Agendamento Particular',
      current_step_id: 'step-2-2',
      current_step_name: 'Etapa 2 — Follow-up 1 (Estudo de Caso)',
      current_step_order: 2,
      status: 'respondido',
      last_sent_at: '2026-09-12T16:00:00Z',
      paused_reason: 'Lead respondeu solicitando proposta detalhada',
    },
    ai_analysis: {
      data_points: [
        'Anuncia no Meta Ads para procedimentos estéticos de alto ticket',
        'Tráfego é direcionado para número pessoal da secretária',
      ],
      inferences: [
        'Alto índice de leads perdidos fora do horário comercial (noites e finais de semana)',
      ],
      recommendations: [
        'Apresentar fluxo de agendamento 24h e LP com carregamento abaixo de 1 segundo',
      ],
      main_hook: 'Captação 24h de pacientes particulares sem sobrecarregar a recepção',
      should_approach: true,
    },
  },
  {
    id: 'lead-3',
    name: 'Eduardo Moreira',
    company_name: 'Moreira Imóveis',
    role: 'Diretor Comercial',
    segment: 'Imobiliárias',
    niche_id: 'niche-3',
    email: 'eduardo@moreiraimoveis.com.br',
    phone: '(11) 97654-1122',
    whatsapp: '5511976541122',
    city: 'Sorocaba',
    state: 'SP',
    score: 68,
    temperature: 'morno',
    status: 'em_abordagem',
    services: ['Automação WhatsApp & Atendimento', 'Site Institucional'],
    last_contact_at: '2026-09-10T09:15:00Z',
    next_action: 'Follow-up atrasado (resolver contato)',
    next_action_at: '2026-09-14T15:00:00Z',
    ai_analysis: {
      data_points: ['Portal de imóveis lento', 'Lead qualification inexistente no site'],
      inferences: ['Corretores perdem tempo com curiosos de locação sem garantia'],
      recommendations: ['Filtro de locação e venda automatizado por bot'],
      main_hook: 'Roteamento instantâneo de compradores qualificados para corretores de plantão',
      should_approach: true,
    },
  },
  {
    id: 'lead-4',
    name: 'Marcos Vinicius',
    company_name: 'Contabilidade Nova Era',
    role: 'Sócio Administrador',
    segment: 'Contabilidade',
    niche_id: 'niche-1',
    email: 'marcos@novaeracontabil.com.br',
    phone: '(21) 98844-3322',
    whatsapp: '5521988443322',
    city: 'Rio de Janeiro',
    state: 'RJ',
    score: 84,
    temperature: 'quente',
    status: 'em_abordagem',
    services: ['Follow-up Automático n8n', 'Site Institucional'],
    last_contact_at: '2026-09-12T10:00:00Z',
    next_action: 'Follow-up automático disparado pela IA — sem resposta em 3 dias',
    next_action_at: '2026-09-15T16:30:00Z',
    sequence_progress: {
      id: 'seq-prog-4',
      lead_id: 'lead-4',
      sequence_id: 'seq-1',
      sequence_name: 'Prospecção Ativa BPO & Contabilidade',
      current_step_id: 'step-1-2',
      current_step_name: 'Etapa 2 — Follow-up 1 (Insight de Conversão)',
      current_step_order: 2,
      status: 'aguardando_resposta',
      last_sent_at: '2026-09-12T10:00:00Z',
      next_due_at: '2026-09-15T16:30:00Z',
    },
    ai_analysis: {
      data_points: ['Atua com clientes PJ Simples Nacional e Lucro Presumido'],
      inferences: ['Sofre com inadimplência em honorários e cobrança manual'],
      recommendations: ['Régua de cobrança automática n8n + renovação de site institucional'],
      main_hook: 'Eliminação da cobrança manual e posicionamento moderno de BPO financeiro',
      should_approach: true,
    },
  },
  {
    id: 'lead-5',
    name: 'Juliana Pires',
    company_name: 'Pires Odontologia Estética',
    role: 'Dentista Responsável',
    segment: 'Clínicas / Odonto / Estética',
    niche_id: 'niche-2',
    email: 'dra.juliana@piresodonto.com.br',
    phone: '(11) 94455-6677',
    whatsapp: '5511944556677',
    city: 'Santo André',
    state: 'SP',
    score: 42,
    temperature: 'frio',
    status: 'novo',
    services: ['Google Meu Negócio & Otimização Local'],
    last_contact_at: '2026-09-08T15:00:00Z',
    next_action: 'Avaliar momento de abordagem',
    ai_analysis: {
      data_points: ['Perfil do Google já atualizado recentemente', 'Site com boa nota no PageSpeed'],
      inferences: ['Baixa propensão de contratação imediata para site'],
      recommendations: ['Não abordar agora com proposta de website. Manter em radar para automação.'],
      main_hook: 'Presença digital atual já estruturada, aguardar novo ciclo',
      should_approach: false,
      reason_if_not: 'Presença digital atual parece estruturada e sem gaps evidentes.',
    },
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    lead_id: 'lead-1',
    lead_name: 'Dr. Roberto Silva',
    company_name: 'Silva Advocacia',
    stage_slug: 'primeiro_contato',
    title: 'Site Jurídico Premium + SEO Local',
    estimated_value: 4750,
    probability: 60,
    score: 92,
    temperature: 'quente',
    priority: 'alta',
    services: ['Site Jurídico / Especializado', 'Google Meu Negócio & Otimização Local'],
    last_interaction: 'Há 2 dias via WhatsApp',
    approach_strategy: 'Enfatizar conformidade OAB e posicionamento de autoridade regional',
  },
  {
    id: 'opp-2',
    lead_id: 'lead-2',
    lead_name: 'Dra. Camila Vasconcelos',
    company_name: 'Clínica Vida',
    stage_slug: 'proposta',
    title: 'Landing Page Cirúrgica + Bot WhatsApp',
    estimated_value: 3500,
    probability: 80,
    score: 88,
    temperature: 'quente',
    priority: 'alta',
    services: ['Landing Page de Alta Conversão', 'Automação WhatsApp & Atendimento'],
    last_interaction: 'Ontem às 11:00',
    approach_strategy: 'Apresentar cálculo de ROI baseado no valor da consulta particular',
  },
  {
    id: 'opp-3',
    lead_id: 'lead-3',
    lead_name: 'Eduardo Moreira',
    company_name: 'Moreira Imóveis',
    stage_slug: 'qualificacao',
    title: 'Automação de Triagem Imobiliária',
    estimated_value: 2400,
    probability: 40,
    score: 68,
    temperature: 'morno',
    priority: 'media',
    services: ['Automação WhatsApp & Atendimento'],
    last_interaction: 'Há 5 dias',
  },
  {
    id: 'opp-4',
    lead_id: 'lead-4',
    lead_name: 'Marcos Vinicius',
    company_name: 'Contabilidade Nova Era',
    stage_slug: 'diagnostico',
    title: 'Plataforma Contábil + Régua n8n',
    estimated_value: 5100,
    probability: 70,
    score: 84,
    temperature: 'quente',
    priority: 'alta',
    services: ['Site Institucional', 'Follow-up Automático n8n'],
    last_interaction: 'Há 3 dias (disparo n8n)',
    n8n_automated: true,
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Dr. Fernando Alcantara',
    company_name: 'Alcantara Cirurgia Plástica',
    segment: 'Clínicas / Odonto / Estética',
    email: 'contato@alcantaracirurgia.com.br',
    phone: '(11) 98111-2233',
    whatsapp: '5511981112233',
    total_contracted: 16800,
    total_received: 16800,
    total_pending: 0,
    lifetime_value: 16800,
    projects_count: 3,
    last_project_at: '2026-07-20',
    status: 'ativo',
    cross_sell_opportunities: ['Agente IA Especialista', 'Manutenção & Evolução Contínua'],
  },
  {
    id: 'cli-2',
    name: 'Beatriz Rezende',
    company_name: 'Rezende & Associados Consultoria',
    segment: 'Consultorias & Serviços B2B',
    email: 'beatriz@rezendeconsultoria.com.br',
    phone: '(11) 99887-4455',
    whatsapp: '5511998874455',
    total_contracted: 12400,
    total_received: 9400,
    total_pending: 3000,
    lifetime_value: 12400,
    projects_count: 2,
    last_project_at: '2026-08-15',
    status: 'ativo',
    cross_sell_opportunities: ['Automação WhatsApp & Atendimento'],
  },
  {
    id: 'cli-3',
    name: 'Lucas Brandão',
    company_name: 'Brandão Engenharia & Laudos',
    segment: 'Engenharia / B2B',
    email: 'lucas@brandaoengenharia.com.br',
    phone: '(19) 97123-9988',
    whatsapp: '5519971239988',
    total_contracted: 8900,
    total_received: 8900,
    total_pending: 0,
    lifetime_value: 8900,
    projects_count: 1,
    last_project_at: '2026-05-10',
    status: 'ativo',
    cross_sell_opportunities: ['Google Meu Negócio & Otimização Local', 'Follow-up Automático n8n'],
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-1',
    code: 'PROP-2026-042',
    client_name: 'Dra. Camila Vasconcelos',
    company_name: 'Clínica Vida',
    subtotal: 4200,
    discount: 700,
    total: 3500,
    installments_count: 3,
    installments_description: 'Entrada de R$ 1.500 + 2x de R$ 1.000 (30 e 60 dias)',
    status: 'enviada',
    created_at: '2026-09-14',
    valid_until: '2026-09-24',
    items: [
      {
        id: 'pi-1',
        service_id: 'srv-2',
        service_name: 'Landing Page de Alta Conversão',
        description: 'Design exclusivo focado nos procedimentos cirúrgicos, copy persuasiva e speed score > 90',
        price: 1800,
        discount: 0,
        total: 1800,
      },
      {
        id: 'pi-2',
        service_id: 'srv-5',
        service_name: 'Automação WhatsApp & Atendimento',
        description: 'Integração direta com o número da clínica, confirmação de presença e triagem rápida',
        price: 2400,
        discount: 700,
        total: 1700,
      },
    ],
  },
  {
    id: 'prop-2',
    code: 'PROP-2026-041',
    client_name: 'Dr. Roberto Silva',
    company_name: 'Silva Advocacia',
    subtotal: 4750,
    discount: 250,
    total: 4500,
    installments_count: 2,
    installments_description: '50% no início e 50% na aprovação final',
    status: 'rascunho',
    created_at: '2026-09-15',
    valid_until: '2026-09-25',
    items: [
      {
        id: 'pi-3',
        service_id: 'srv-3',
        service_name: 'Site Jurídico / Especializado',
        description: 'Portal completo com áreas de atuação, artigos técnicos e layout editorial sóbrio',
        price: 3800,
        discount: 0,
        total: 3800,
      },
      {
        id: 'pi-4',
        service_id: 'srv-9',
        service_name: 'Google Meu Negócio & Otimização Local',
        description: 'Estruturação de palavras-chave jurídicas e geolocalização estratégica',
        price: 950,
        discount: 250,
        total: 700,
      },
    ],
  },
];

export const INITIAL_CONTRATOS: Contract[] = [
  {
    id: 'cont-1',
    code: 'CONT-2026-018',
    client_name: 'Beatriz Rezende',
    company_name: 'Rezende & Associados Consultoria',
    services_summary: 'Site Institucional + Consultoria Estratégica Digital',
    total_amount: 5400,
    status: 'assinado',
    signed_at: '2026-08-16',
    signature_provider: 'Clicksign',
    start_date: '2026-08-18',
    end_date: '2026-09-30',
  },
  {
    id: 'cont-2',
    code: 'CONT-2026-019',
    client_name: 'Dr. Fernando Alcantara',
    company_name: 'Alcantara Cirurgia Plástica',
    services_summary: 'Automação WhatsApp & Atendimento + Agente IA Especialista',
    total_amount: 5900,
    status: 'aguardando_assinatura',
    signature_provider: 'Clicksign',
    start_date: '2026-09-10',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    client_name: 'Beatriz Rezende',
    company_name: 'Rezende & Associados Consultoria',
    name: 'Redesenho Portal Corporativo Rezende',
    status: 'em_desenvolvimento',
    start_date: '2026-08-20',
    deadline: '2026-09-22',
    progress_percentage: 75,
    services: [
      {
        service_name: 'Site Institucional',
        checklist: [
          { item: 'Estrutura de wireframe aprovada', completed: true },
          { item: 'Identidade visual e tipografia aplicadas', completed: true },
          { item: 'Implementação Next.js & Tailwind CSS', completed: true },
          { item: 'Otimização de SEO técnico & Core Web Vitals', completed: false },
          { item: 'Homologação final com o cliente', completed: false },
        ],
      },
    ],
  },
  {
    id: 'proj-2',
    client_name: 'Dr. Fernando Alcantara',
    company_name: 'Alcantara Cirurgia Plástica',
    name: 'Agente de Triagem & Automação de Agendamentos',
    status: 'briefing',
    start_date: '2026-09-12',
    deadline: '2026-10-05',
    progress_percentage: 20,
    services: [
      {
        service_name: 'Automação WhatsApp & Atendimento',
        checklist: [
          { item: 'Mapeamento das perguntas frequentes de procedimentos', completed: true },
          { item: 'Definição do tom de voz e regras de triagem', completed: false },
          { item: 'Configuração dos webhooks n8n com Evolution API', completed: false },
        ],
      },
    ],
  },
];

export const INITIAL_HISTORICAL_PROJECTS: HistoricalProject[] = [
  {
    id: 'hist-1',
    client_name: 'Marcos Aurelio',
    company_name: 'Aurelio Advocacia Trabalhista',
    services_summary: 'Site Institucional + Google Meu Negócio',
    amount_contracted: 4150,
    amount_received: 4150,
    amount_pending: 0,
    project_date: '2024-03-12',
    status: 'concluido',
    notes: 'Primeiro projeto no segmento jurídico. Excelente indicação posterior.',
  },
  {
    id: 'hist-2',
    client_name: 'Luciana Prado',
    company_name: 'Studio Prado Dermatologia',
    services_summary: 'Landing Page + Automação WhatsApp',
    amount_contracted: 3900,
    amount_received: 3900,
    amount_pending: 0,
    project_date: '2024-08-20',
    status: 'concluido',
  },
  {
    id: 'hist-3',
    client_name: 'Carlos Mendes',
    company_name: 'Mendes Transportes & Logística',
    services_summary: 'Portal Web + Sistema de Rastreamento Interno',
    amount_contracted: 9800,
    amount_received: 9800,
    amount_pending: 0,
    project_date: '2025-01-15',
    status: 'concluido',
  },
  {
    id: 'hist-4',
    client_name: 'Patricia Lima',
    company_name: 'Lima & Associados Contabilidade',
    services_summary: 'Site Institucional + Integração CRM',
    amount_contracted: 5200,
    amount_received: 5200,
    amount_pending: 0,
    project_date: '2025-05-18',
    status: 'concluido',
  },
  {
    id: 'hist-5',
    client_name: 'Rafael Guimarães',
    company_name: 'Guimarães Imóveis Prime',
    services_summary: 'Portal Imobiliário + Filtros Avançados',
    amount_contracted: 7600,
    amount_received: 7600,
    amount_pending: 0,
    project_date: '2025-10-05',
    status: 'concluido',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpItem[] = [
  {
    id: 'fu-1',
    target_name: 'Dr. Roberto Silva',
    company_name: 'Silva Advocacia',
    context: 'Lead quente sem resposta após abertura institucional há 2 dias',
    due_date: 'Hoje, 17:00',
    next_action: 'Apresentar estudo de caso em conformidade OAB',
    is_automated: false,
    type: 'hoje',
    status: 'pendente',
  },
  {
    id: 'fu-2',
    target_name: 'Eduardo Moreira',
    company_name: 'Moreira Imóveis',
    context: 'Retorno sobre demonstração de filtro de corretores no WhatsApp',
    due_date: 'Ontem, 15:00',
    next_action: 'Cobrar posicionamento se vão manter o projeto para este mês',
    is_automated: false,
    type: 'atrasado',
    status: 'atrasado',
  },
  {
    id: 'fu-3',
    target_name: 'Marcos Vinicius',
    company_name: 'Contabilidade Nova Era',
    context: 'Follow-up automático n8n disparado (Etapa 2 - Follow-up 1)',
    due_date: 'Hoje, 16:30',
    next_action: 'Aguardar resposta no WhatsApp ou enviar áudio rápido',
    is_automated: true,
    type: 'automatico',
    status: 'pendente',
  },
  {
    id: 'fu-4',
    target_name: 'Dra. Camila Vasconcelos',
    company_name: 'Clínica Vida',
    context: 'Proposta PROP-2026-042 (R$ 3.500) visualizada há 24h',
    due_date: 'Amanhã, 14:00',
    next_action: 'Tirar dúvidas de parcelamento em 3x e alinhar início',
    is_automated: false,
    type: 'proximo',
    status: 'pendente',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'tsk-1',
    title: 'Validar Core Web Vitals e responsividade mobile',
    related_to: 'Rezende & Associados Consultoria',
    due_date: '2026-09-18',
    status: 'em_andamento',
    priority: 'alta',
  },
  {
    id: 'tsk-2',
    title: 'Finalizar mapa de intenções do bot de atendimento',
    related_to: 'Alcantara Cirurgia Plástica',
    due_date: '2026-09-20',
    status: 'pendente',
    priority: 'alta',
  },
  {
    id: 'tsk-3',
    title: 'Subir proposta comercial formalizada no sistema',
    related_to: 'Silva Advocacia',
    due_date: '2026-09-16',
    status: 'pendente',
    priority: 'media',
  },
  {
    id: 'tsk-4',
    title: 'Configurar webhook de notificação de pagamento Pix',
    related_to: 'Infraestrutura n8n EvoPixel',
    due_date: '2026-09-22',
    status: 'pendente',
    priority: 'media',
  },
];

export const INITIAL_FINANCIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'fin-1',
    title: 'Projeto Portal Corporativo - Parcela 2/2',
    client_name: 'Rezende & Associados Consultoria',
    category: 'Serviço Website',
    amount_contracted: 3000,
    amount_received: 0,
    amount_pending: 3000,
    due_date: '2026-09-30',
    status: 'pendente',
  },
  {
    id: 'fin-2',
    title: 'Projeto Portal Corporativo - Entrada',
    client_name: 'Rezende & Associados Consultoria',
    category: 'Serviço Website',
    amount_contracted: 2400,
    amount_received: 2400,
    amount_pending: 0,
    due_date: '2026-08-18',
    status: 'pago',
  },
  {
    id: 'fin-3',
    title: 'Automação & Treinamento IA - Parcela 1/2',
    client_name: 'Alcantara Cirurgia Plástica',
    category: 'Automação',
    amount_contracted: 2950,
    amount_received: 2950,
    amount_pending: 0,
    due_date: '2026-09-10',
    status: 'pago',
  },
  {
    id: 'fin-4',
    title: 'Consultoria Estratégica & Diagnóstico',
    client_name: 'Brandão Engenharia & Laudos',
    category: 'Presença Digital',
    amount_contracted: 2200,
    amount_received: 2200,
    amount_pending: 0,
    due_date: '2026-08-05',
    status: 'pago',
  },
  {
    id: 'fin-5',
    title: 'Manutenção Mensal & Hospedagem Premium (Setembro)',
    client_name: 'Alcantara Cirurgia Plástica',
    category: 'Recorrência Mensal',
    amount_contracted: 450,
    amount_received: 450,
    amount_pending: 0,
    due_date: '2026-09-05',
    status: 'pago',
  },
];

export const INITIAL_MESSAGE_LOGS: MessageLog[] = [
  {
    id: 'ml-1',
    lead_id: 'lead-4',
    step_name: 'Etapa 1 — Abertura Consultiva',
    channel: 'WhatsApp (Evolution API)',
    sent_text: 'Olá Marcos, tudo bem? Notei que a Contabilidade Nova Era tem forte atuação no Rio de Janeiro, mas ao pesquisar encontrei apenas um perfil básico sem canal de pré-qualificação ágil. Vocês hoje perdem muito tempo triando clientes que chegam pelo WhatsApp sem perfil financeiro?',
    direction: 'enviada',
    sent_at: '2026-09-10T10:00:00Z',
    source: 'automatica_n8n',
    status: 'lida',
  },
  {
    id: 'ml-2',
    lead_id: 'lead-4',
    step_name: 'Etapa 2 — Follow-up 1 (Insight de Conversão)',
    channel: 'WhatsApp (Evolution API)',
    sent_text: 'Marcos, passando rápido: na semana passada estruturamos um fluxo no WhatsApp para outro escritório que filtrou 65% das dúvidas repetitivas e já entregou o lead pronto com faturamento estimado. Faz sentido mostrar um resumo de 3 min em áudio ou vídeo?',
    direction: 'enviada',
    sent_at: '2026-09-12T10:00:00Z',
    source: 'automatica_n8n',
    status: 'entregue',
  },
  {
    id: 'ml-3',
    lead_id: 'lead-2',
    step_name: 'Etapa 1 — Abertura (Velocidade de Resposta)',
    channel: 'WhatsApp (Evolution API)',
    sent_text: 'Olá Dra. Camila, tudo bem? Vi o posicionamento da Clínica Vida em Campinas. Fiz um teste rápido na busca local e reparei que vocês não possuem confirmação e agendamento instantâneo via WhatsApp...',
    direction: 'enviada',
    sent_at: '2026-09-11T14:20:00Z',
    source: 'automatica_n8n',
    status: 'lida',
  },
  {
    id: 'ml-4',
    lead_id: 'lead-2',
    channel: 'WhatsApp',
    sent_text: 'Olá! Achei muito interessante a colocação de vocês. Nossa recepção realmente fica sobrecarregada às segundas-feiras com agendamentos. Vocês conseguem me enviar uma proposta com os valores?',
    direction: 'recebida',
    sent_at: '2026-09-13T09:12:00Z',
    source: 'manual',
    status: 'entregue',
  },
];

export const INITIAL_INSIGHTS: BusinessInsight[] = [
  {
    id: 'ins-1',
    title: 'O nicho Contabilidade responde 3x mais no Follow-up 1 do que na Abertura',
    description: 'Apresentar números concretos de redução de trabalho manual na Etapa 2 aumentou o retorno de 11% para 34% neste nicho.',
    category: 'Prospecção',
    metric: '+23% taxa de resposta',
    action_label: 'Ver Sequência do Nicho',
    link: '/prospeccao/mensagens',
  },
  {
    id: 'ins-2',
    title: 'Seu ticket médio cresceu 18% em relação ao período anterior',
    description: 'Propostas com a combinação Website Institucional + Automação de WhatsApp elevaram o ticket médio para R$ 4.280.',
    category: 'Vendas',
    metric: 'R$ 4.280 ticket médio',
    action_label: 'Ver Relatório de Vendas',
    link: '/relatorios',
  },
  {
    id: 'ins-3',
    title: 'Automação já representa 28% do faturamento acumulado',
    description: 'Serviços de IA e automação n8n tiveram o maior crescimento percentual nos últimos 4 meses.',
    category: 'Serviços',
    metric: '28% da receita',
    action_label: 'Catálogo de Serviços',
    link: '/servicos',
  },
  {
    id: 'ins-4',
    title: 'Você possui R$ 15.750 em oportunidades ativas no pipeline',
    description: '4 oportunidades com probabilidade média de 68% de fechamento neste trimestre.',
    category: 'Pipeline',
    metric: 'R$ 15.750 aberto',
    action_label: 'Abrir Pipeline Kanban',
    link: '/pipeline',
  },
];

export const INITIAL_PROSPECTS: Prospect[] = [
  {
    id: 'prosp-1',
    nome: 'Dra. Camila Vasconcelos',
    empresa: 'Clínica Dermatológica DermaLux',
    telefone: '(11) 98234-1122',
    whatsapp: '5511982341122',
    email: 'contato@dermalux.med.br',
    site: 'http://dermaluxclinica.com.br',
    instagram: '@dermalux_dermato',
    cidade: 'São Paulo',
    estado: 'SP',
    segment: 'Clínicas / Odonto / Estética',
    icp_score: 94,
    opportunity_score: 92,
    digital_presence_score: 45,
    observations: 'Site lento em mobile, botão de WhatsApp não funciona, Instagram com 14k seguidores muito ativo.',
    source: 'Prospecção Ativa IA',
    suggested_service: 'Landing Page de Alta Conversão + Automação WhatsApp',
    identified_signals: [
      'Site desatualizado sem responsividade mobile adequada',
      'WhatsApp pouco acessível no topo da página',
      'Instagram com alto engajamento mas sem funil de conversão',
      'Segmento com ticket médio alto de procedimentos estéticos',
    ],
    status: 'priority',
    created_at: '2026-09-14T08:30:00Z',
    updated_at: '2026-09-15T11:20:00Z',
  },
  {
    id: 'prosp-2',
    nome: 'Marcos Vinicius',
    empresa: 'Audicont Assessoria Contábil',
    telefone: '(41) 99123-4567',
    whatsapp: '5541991234567',
    email: 'marcos@audicont.com.br',
    site: 'http://audicontassessoria.com.br',
    cidade: 'Curitiba',
    estado: 'PR',
    segment: 'Contabilidade',
    icp_score: 89,
    opportunity_score: 86,
    digital_presence_score: 40,
    observations: 'Contabilidade com 80+ clientes PJ, processo de onboarding de clientes ainda via e-mail e formulário manual.',
    source: 'Prospecção Ativa IA',
    suggested_service: 'Automação n8n de Onboarding + Portal Institucional',
    identified_signals: [
      'Ausência de automação no acolhimento de novos clientes',
      'Site institucional de 2019 sem SEO técnico',
      'Nicho com resposta comprovada na Etapa 2 de abordagem',
    ],
    status: 'priority',
    created_at: '2026-09-13T10:00:00Z',
    updated_at: '2026-09-14T14:10:00Z',
  },
  {
    id: 'prosp-3',
    nome: 'Rogério Siqueira',
    empresa: 'Siqueira Prime Imóveis',
    telefone: '(19) 98877-6655',
    whatsapp: '5519988776655',
    email: 'rogerio@siqueiraprime.com.br',
    site: 'http://siqueiraprime.com.br',
    instagram: '@siqueira_prime_imoveis',
    cidade: 'Campinas',
    estado: 'SP',
    segment: 'Imobiliárias',
    icp_score: 84,
    opportunity_score: 81,
    digital_presence_score: 55,
    observations: 'Forte presença em imóveis de alto padrão. Perdem leads aos finais de semana por falta de triagem rápida.',
    source: 'Prospecção Ativa IA',
    suggested_service: 'Agente IA Especialista de Triagem WhatsApp',
    identified_signals: [
      'Tempo de resposta em finais de semana superior a 4 horas',
      'Google Meu Negócio sem avaliações recentes respondidas',
      'Volume estimado de 15 leads perdidos por mês por demora',
    ],
    status: 'priority',
    created_at: '2026-09-12T09:15:00Z',
    updated_at: '2026-09-14T16:00:00Z',
  },
  {
    id: 'prosp-4',
    nome: 'Fabiana Toledo',
    empresa: 'Toledo & Cunha Consultoria Tributária',
    telefone: '(11) 97333-8899',
    whatsapp: '5511973338899',
    email: 'fabiana@toledocunha.com.br',
    site: 'http://toledocunha.adv.br',
    cidade: 'São Paulo',
    estado: 'SP',
    segment: 'Consultorias & Serviços B2B',
    icp_score: 78,
    opportunity_score: 74,
    digital_presence_score: 60,
    observations: 'Boutique tributária conceituada buscando posicionamento digital mais nobre para prospecção passiva.',
    source: 'Google Maps / Busca Orgânica',
    suggested_service: 'Site Institucional Premium + Otimização de SEO',
    identified_signals: [
      'Identidade visual datada não condizente com o ticket cobrado',
      'Autoridade técnica elevada no segmento',
    ],
    status: 'analyzed',
    created_at: '2026-09-11T14:20:00Z',
    updated_at: '2026-09-13T09:00:00Z',
  },
  {
    id: 'prosp-5',
    nome: 'Dr. Thiago Meirelles',
    empresa: 'Meirelles Odontologia Avançada',
    telefone: '(11) 99444-5566',
    whatsapp: '5511994445566',
    email: 'recepcao@meirellesodonto.com.br',
    site: 'http://meirellesodonto.com.br',
    cidade: 'São Paulo',
    estado: 'SP',
    segment: 'Clínicas / Odonto / Estética',
    icp_score: 71,
    opportunity_score: 69,
    digital_presence_score: 50,
    observations: 'Clínica de implantes com 4 consultórios. Necessita de automação de confirmação de consultas para reduzir no-show.',
    source: 'Indicação',
    suggested_service: 'Automação de Confirmação de Consultas n8n',
    identified_signals: [
      'Taxa de no-show relatada em torno de 22%',
      'Secretárias gastam 3h/dia confirmando consultas manualmente',
    ],
    status: 'new',
    created_at: '2026-09-15T09:00:00Z',
    updated_at: '2026-09-15T09:00:00Z',
  },
];

export const INITIAL_BUSINESS_CONTEXT: BusinessContext = {
  id: 'ctx-1',
  nome_empresa: 'EvoPixel',
  descricao: 'Estúdio boutique de desenvolvimento de software, automação inteligente e presença digital premium para empresas que exigem autoridade e conversão.',
  servicos: [
    'Site Institucional',
    'Landing Page de Alta Conversão',
    'Automação WhatsApp & Atendimento',
    'Agente IA Especialista',
    'Integração de Sistemas & Webhooks (n8n)',
    'Identidade Visual & Direção de Arte',
    'Google Meu Negócio & Otimização Local',
  ],
  ticket_medio: 4280,
  icp: {
    tamanho_empresa: '5 a 50 colaboradores',
    faturamento_estimado: 'R$ 50.000 a R$ 500.000 / mês',
    decisor: 'Sócio-fundador, Diretor Comercial, Head Médico ou Gestor Operacional',
    presenca_digital: 'Ativa mas com gargalos técnicos (site desatualizado, falta de automação no atendimento ou perda de leads)',
  },
  nichos_prioritarios: [
    'Clínicas Médicas / Odonto / Estética',
    'Contabilidade & Finanças B2B',
    'Imobiliárias & Corretores de Alto Padrão',
    'Consultorias & Serviços B2B',
  ],
  regiao_atuacao: 'Brasil (Remoto com atendimento presencial São Paulo e Curitiba)',
  objetivos: [
    'Consolidar o posicionamento editorial premium',
    'Aumentar o ticket médio de novos projetos para R$ 5.500',
    'Elevar a retenção por meio de contratos de automação contínua',
  ],
  metas: [
    'R$ 15.000 de receita no mês corrente',
    '8 novos clientes fechados',
    'Taxa de resposta de prospecção superior a 15%',
  ],
  regras_comerciais: [
    'Não conceder desconto à vista superior a 10%',
    'Propostas válidas por no máximo 10 dias corridos',
    'Início de desenvolvimento somente após 50% de entrada ou contrato assinado',
    'Toda oportunidade prioritária sem interação há 48h exige follow-up imediato',
  ],
  tom_comunicacao: 'Editorial, consultivo, sóbrio, analítico e sem jargões superficiais.',
  servicos_prioritarios: [
    'Site Institucional + Automação WhatsApp',
    'Agente IA Especialista n8n',
    'Landing Page de Alta Conversão',
  ],
  servicos_evitar: [
    'Projetos pontuais de baixa complexidade com ticket abaixo de R$ 1.500',
    'Manutenção avulsa sem contrato mensal',
  ],
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-09-15T00:00:00Z',
};

export const INITIAL_COMMERCIAL_GOALS: CommercialGoal = {
  id: 'goal-2026-03',
  periodo: 'Março 2026',
  faturamento_alvo: 15000,
  faturamento_atual: 8800,
  novos_clientes_alvo: 8,
  novos_clientes_atual: 3,
  propostas_alvo: 20,
  propostas_atual: 7,
  leads_qualificados_alvo: 40,
  leads_qualificados_atual: 19,
  prospeccoes_alvo: 100,
  prospeccoes_atual: 64,
  status: 'em_progresso',
};

export const INITIAL_CONVERSATION_SUMMARIES: ConversationSummary[] = [
  {
    id: 'sum-1',
    conversation_id: 'conv-1',
    lead_id: 'lead-1',
    lead_name: 'Dr. Roberto Mendonça',
    company_name: 'Clínica Vida & Saúde',
    summary: 'Lead demonstrou forte insatisfação com a perda de agendamentos no WhatsApp durante finais de semana. Solicitou detalhamento sobre a triagem com Agente IA e o prazo de entrega da Landing Page.',
    intent: 'solicitar_proposta',
    lead_temperature: 'quente',
    lead_score: 92,
    services_detected: ['Landing Page de Alta Conversão', 'Agente IA Especialista'],
    objections: ['Preocupação com tom humanizado do bot'],
    next_action: 'Enviar proposta detalhada com gravação de demonstração do bot de triagem',
    ai_confidence: 0.94,
    updated_at: '2026-09-15T15:30:00Z',
  },
  {
    id: 'sum-2',
    conversation_id: 'conv-2',
    lead_id: 'lead-2',
    lead_name: 'Mariana Duarte',
    company_name: 'Duarte & Associados Contabilidade',
    summary: 'Respondeu à Etapa 2 da sequência de prospecção. Confirmou que a recepção fica sobrecarregada às segundas-feiras com rotinas manuais de acolhimento fiscal.',
    intent: 'interesse_comercial',
    lead_temperature: 'quente',
    lead_score: 88,
    services_detected: ['Automação WhatsApp & Atendimento', 'Site Institucional'],
    objections: ['Necessidade de aprovação do sócio sênior'],
    next_action: 'Agendar diagnóstico técnico de 20 minutos com os dois sócios',
    ai_confidence: 0.91,
    updated_at: '2026-09-14T11:00:00Z',
  },
];

export const INITIAL_NEXT_BEST_ACTIONS: NextBestAction[] = [
  {
    id: 'nba-1',
    entity_type: 'lead',
    entity_id: 'lead-1',
    entity_name: 'Dr. Roberto Mendonça (Clínica Vida)',
    action_title: 'Enviar proposta comercial formalizada',
    reason: 'Lead qualificado como quente (Score 92) com interesse confirmado em Landing Page + Agente IA sem proposta enviada há 24h.',
    action_label: 'Gerar Proposta',
    action_link: '/propostas',
    priority: 'alta',
    data_source: 'Leads + Conversas n8n + Histórico de Mensagens',
  },
  {
    id: 'nba-2',
    entity_type: 'opportunity',
    entity_id: 'opp-2',
    entity_name: 'Moreira Imóveis',
    action_title: 'Disparar follow-up de retorno de proposta',
    reason: 'Proposta de R$ 4.750 enviada há 3 dias corridos sem visualização registrada nas últimas 48 horas.',
    action_label: 'Enviar Follow-up',
    action_link: '/follow-ups',
    priority: 'alta',
    data_source: 'Pipeline Kanban + Propostas Comerciais',
  },
  {
    id: 'nba-3',
    entity_type: 'client',
    entity_id: 'cli-1',
    entity_name: 'Alcantara Cirurgia Plástica',
    action_title: 'Apresentar cross-sell de Agente IA Especialista',
    reason: 'Cliente ativo com LTV de R$ 16.800 e projeto concluído há 60 dias sem novo contrato vigente.',
    action_label: 'Ver Cliente 360',
    action_link: '/clientes/cli-1',
    priority: 'media',
    data_source: 'Clientes 360 + Financeiro Acumulado',
  },
];

export const INITIAL_EVO_INSIGHTS: EvoInsightItem[] = [
  {
    id: 'evo-ins-1',
    type: 'DADO',
    title: 'R$ 8.400 em propostas aguardando retorno formal',
    explanation: 'Existem 2 propostas ativas enviadas nos últimos 7 dias cujo prazo de validade expira em menos de 72 horas.',
    period: 'Últimos 7 dias',
    data_source: 'Módulo de Propostas + Pipeline de Vendas',
    suggested_action: {
      label: 'Ver Propostas Pendentes',
      link: '/propostas',
    },
  },
  {
    id: 'evo-ins-2',
    type: 'INFERENCIA',
    title: 'O nicho Contabilidade responde com 3.1x mais engajamento ao Follow-up 1',
    explanation: 'Ao analisar 18 abordagens no nicho, a menção a "redução de horas operacionais no acolhimento" gerou 34% de taxa de resposta contra 11% na abertura genérica.',
    period: 'Últimos 30 dias',
    data_source: 'Banco de Mensagens + Logs n8n',
    suggested_action: {
      label: 'Ver Sequência de Contabilidade',
      link: '/prospeccao/mensagens',
    },
  },
  {
    id: 'evo-ins-3',
    type: 'RECOMENDACAO',
    title: 'Priorizar abordagem nos 3 prospects com ICP superior a 85 hoje',
    explanation: 'Clínica Dermatológica DermaLux, Audicont e Siqueira Prime possuem alta probabilidade de conversão baseada nos gargalos digitais detectados.',
    period: 'Hoje',
    data_source: 'Base de Prospects + Diagnóstico de Sinais Digitais',
    suggested_action: {
      label: 'Ver Prospects Recomendados',
      link: '/prospects',
    },
  },
  {
    id: 'evo-ins-4',
    type: 'DADO',
    title: '58,7% da meta mensal de faturamento atingida',
    explanation: 'Faturamento realizado de R$ 8.800 frente à meta de R$ 15.000 para o ciclo de Março de 2026. Restam R$ 6.200 a serem contratados.',
    period: 'Mês Atual (Março 2026)',
    data_source: 'Financeiro + Metas Comerciais',
    suggested_action: {
      label: 'Ver Painel de Metas',
      link: '/relatorios',
    },
  },
];

export const INITIAL_AI_COMMANDS: AICommand[] = [
  {
    id: 'cmd-1',
    session_id: 'sess-1',
    intent: 'get_conversion_rate',
    input: 'Como está nossa taxa de conversão?',
    tool_used: 'get_conversion_rate',
    permission_level: 'READ',
    parameters: { period: '30d' },
    result: {
      leads_total: 84,
      qualified_opportunities: 19,
      sales: 6,
      conversion_rate: 7.14,
      previous_rate: 5.7,
    },
    status: 'success',
    created_at: '2026-09-15T14:10:00Z',
  },
  {
    id: 'cmd-2',
    session_id: 'sess-1',
    intent: 'register_payment',
    input: 'Registrar pagamento de R$ 2.000 da Clínica Vida',
    tool_used: 'register_payment',
    permission_level: 'WRITE',
    parameters: {
      client_name: 'Clínica Vida & Saúde',
      amount: 2000,
      payment_method: 'pix',
    },
    result: {
      status: 'pago',
      amount: 2000,
      transaction_id: 'tx-2',
    },
    status: 'success',
    created_at: '2026-09-15T16:40:00Z',
  },
];

export const INITIAL_AI_ACTION_LOGS: AIActionLog[] = [
  {
    id: 'act-1',
    command_id: 'cmd-2',
    action_type: 'register_payment',
    entity_type: 'payment',
    entity_id: 'tx-2',
    entity_label: 'Clínica Vida & Saúde — R$ 2.000 (PIX)',
    before_data: { status: 'pendente', amount_pending: 2000 },
    after_data: { status: 'pago', amount_received: 2000, amount_pending: 0 },
    created_at: '2026-09-15T16:40:05Z',
  },
];

